import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  bool _isTamil = false;
  bool get isTamil => _isTamil;

  void toggleLanguage() {
    _isTamil = !_isTamil;
    notifyListeners();
  }

  String translate(String key) {
    if (!_isTamil) return _en[key] ?? key;
    return _ta[key] ?? _en[key] ?? key;
  }

  static const Map<String, String> _en = {
    'dashboard': 'Dashboard',
    'milk_entry': 'Milk Entry',
    'milk_history': 'Milk History',
    'cattle_list': 'Cattle List',
    'financials': 'Financials',
    'total_cows': 'Total Cows',
    'today_milk': 'Today\'s Milk',
    'net_balance': 'Net Balance',
    'quick_actions': 'Quick Actions',
    'add_milk': 'Add Milk',
    'add_expense': 'Add Expense',
    'add_cow': 'Add Cow',
    'add_payment': 'Add Payment',
    'breeding_inj': 'Breeding Inj.',
    'alerts': 'Alerts',
    'from_yesterday': 'from yesterday',
    'same_as_yesterday': 'Same as yesterday',
    'overall_profit': 'Overall Profit/Loss',
    'tap_to_switch': 'தமிழ்',
    'add_health_record': 'Medical Record',
    'export_reports': 'Export Reports',
    'farm_calendar': 'Farm Calendar',
    'settings': 'Settings',
    'income': 'Income',
    'expense': 'Expense',
    'weather_forecast': 'Weather',
    'sell_cow': 'Sell Cow',
    'dry_cow': 'Dry Cow',
    'todo_list': 'To-Do List',
    'purchase_cow': 'Purchase Log',
    'vet_contacts': 'Vet Contacts',
    'custom_reminders': 'Custom Reminders',
    'budget_manager': 'Budget Manager',
    'login_title': 'Welcome to KRB Dairy',
    'login_subtitle': 'Sign in to access your farm data',
    'tab_password': 'Password',
    'tab_otp': 'Email OTP',
    'email_label': 'Email Address',
    'password_label': 'Password',
    'otp_label': '6-Digit OTP Code',
    'btn_signin': 'Sign In',
    'btn_send_otp': 'Send OTP',
    'btn_verify_otp': 'Verify & Sign In',
    'btn_resend_otp': 'Resend OTP',
    'btn_resend_countdown': 'Resend in {seconds}s',
    'err_invalid_email': 'Please enter a valid email address',
    'err_invalid_password': 'Password must be at least 6 characters',
    'err_invalid_otp': 'Please enter a valid 6-digit OTP code',
    'logout': 'Logout',
    'logout_confirm': 'Are you sure you want to log out?',
    'logout_subtitle': 'You will need to sign in again to access the app',
    'cancel': 'Cancel',
    'account': 'Account',
    'signed_in_as': 'Signed in as',
    'privacy_policy': 'Privacy Policy',
    'terms_conditions': 'Terms & Conditions',
    'agree_and': ' and ',
    'agree_to_policies_prefix': 'I agree to the ',
    'agree_to_policies_suffix': '',
    'agree_err': 'Please agree to the Terms & Conditions and Privacy Policy to login.',
  };

  static const Map<String, String> _ta = {
    'dashboard': 'முகப்பு',
    'milk_entry': 'பால் பதிவு 🥛',
    'milk_history': 'பால் வரலாறு 📅',
    'cattle_list': 'பசுக்கள் பட்டியல் 🐄',
    'financials': 'நிதி நிலைமை 💰',
    'total_cows': 'மொத்த பசுக்கள்',
    'today_milk': 'இன்றைய பால்',
    'net_balance': 'மொத்த இருப்பு',
    'quick_actions': 'வேகமான செயல்கள்',
    'add_milk': 'பால் சேர் 🥛',
    'add_expense': 'செலவு சேர் 💸',
    'add_cow': 'பசு சேர் 🐄',
    'add_payment': 'பணம் சேர் 💰',
    'breeding_inj': 'இனவிருத்தி 💉',
    'alerts': 'அறிவிப்புகள் 🔔',
    'from_yesterday': 'நேற்றிலிருந்து',
    'same_as_yesterday': 'நேற்று போலவே',
    'overall_profit': 'மொத்த லாபம்/நஷ்டம்',
    'tap_to_switch': 'English',
    'add_health_record': 'மருத்துவ பதிவு 🩺',
    'export_reports': 'அறிக்கை தரவிறக்கம் 📄',
    'farm_calendar': 'பண்ணை நாட்காட்டி 📅',
    'settings': 'அமைப்புகள் ⚙️',
    'income': 'வருமானம்',
    'expense': 'செலவு',
    'weather_forecast': 'வானிலை 🌤️',
    'sell_cow': 'பசு விற்பனை 💰',
    'dry_cow': 'வறட்சி பதிவு 🥛',
    'todo_list': 'வேலை பட்டியல் 📝',
    'purchase_cow': 'பசு கொள்முதல் 🛒',
    'vet_contacts': 'கால்நடை மருத்துவர் 👨‍⚕️',
    'custom_reminders': 'நினைவூட்டல்கள் ⏰',
    'budget_manager': 'பட்ஜெட் மேலாளர் 💼',
    'login_title': 'KRB பண்ணைக்கு வரவேற்கிறோம்',
    'login_subtitle': 'பண்ணைத் தரவை அணுக உள்நுழையவும்',
    'tab_password': 'கடவுச்சொல்',
    'tab_otp': 'மின்னஞ்சல் OTP',
    'email_label': 'மின்னஞ்சல் முகவரி',
    'password_label': 'கடவுச்சொல்',
    'otp_label': '6-இலக்க OTP குறியீடு',
    'btn_signin': 'உள்நுழைக',
    'btn_send_otp': 'OTP அனுப்பு',
    'btn_verify_otp': 'சரிபார்த்து உள்நுழைக',
    'btn_resend_otp': 'மீண்டும் OTP அனுப்பு',
    'btn_resend_countdown': 'Resend in {seconds}s', // countdown text
    'err_invalid_email': 'சரியான மின்னஞ்சலை உள்ளிடவும்',
    'err_invalid_password': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
    'err_invalid_otp': 'சரியான 6-இலக்க OTP குறியீட்டை உள்ளிடவும்',
    'logout': 'வெளியேறு',
    'logout_confirm': 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
    'logout_subtitle': 'செயலியை அணுக மீண்டும் உள்நுழைய வேண்டும்',
    'cancel': 'இரத்து',
    'account': 'கணக்கு',
    'signed_in_as': 'உள்நுழைந்துள்ள மின்னஞ்சல்',
    'privacy_policy': 'தனியுரிமைக் கொள்கை',
    'terms_conditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    'agree_and': ' மற்றும் ',
    'agree_to_policies_prefix': 'நான் ',
    'agree_to_policies_suffix': ' ஆகியவற்றை ஒப்புக்கொள்கிறேன்.',
    'agree_err': 'உள்நுழைவதற்கு முன் விதிமுறைகளை ஒப்புக்கொள்ளவும்.',
  };
}

